### ISSUE TITLE
yolov5-TPH运行错误

### ISSUE THREAD

**Issue by wj51** [Gumpest/YOLOv5-Multibackbone-Compression#18]
您好，我运行yolov5n，s，m，l都没问题，但是运行yolov5x-TPH，yolov5m-TPH-std，yolov5x时出现错误如下：
File "/wangjun/TPH_yolo/train.py", line 656, in <module>
    main(opt)
  File "/wangjun/TPH_yolo/train.py", line 553, in main
    train(opt.hyp, opt, device, callbacks)
  File "/wangjun/TPH_yolo/train.py", line 132, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/wangjun/TPH_yolo/models/yolo.py", line 103, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch], pruning=pruning)  # model, savelist
  File "/wangjun/TPH_yolo/models/yolo.py", line 305, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
  File "/wangjun/TPH_yolo/models/common.py", line 419, in __init__
    self.m = nn.Sequential(*[Bottleneck(c1_, c1_, shortcut, g, e=rate[i]) for i in range(n)])
  File "/wangjun/TPH_yolo/models/common.py", line 419, in <listcomp>
    self.m = nn.Sequential(*[Bottleneck(c1_, c1_, shortcut, g, e=rate[i]) for i in range(n)])
IndexError: list index out of range

**Comment by Gumpest** [comment]
您好，是剪枝功能merge时不兼容造成的，我们会尽快fix

**Comment by Gumpest** [comment]
已经修复，请git pull

**Comment by wj51** [comment]
> 已经修复，请git pull

感谢您的回复，yolox系列运行都成功了，但yolov5xTPH出现新的错误：
Traceback (most recent call last):
  File "/wangjun/TPH_yolo/train.py", line 655, in <module>
    main(opt)
  File "/wangjun/TPH_yolo/train.py", line 552, in main
    train(opt.hyp, opt, device, callbacks)
  File "/wangjun/TPH_yolo/train.py", line 132, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/wangjun/TPH_yolo/models/yolo.py", line 112, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "/wangjun/TPH_yolo/models/yolo.py", line 128, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/wangjun/TPH_yolo/models/yolo.py", line 152, in _forward_once
    x = m(x)  # run
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/wangjun/TPH_yolo/models/common.py", line 423, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/wangjun/TPH_yolo/models/common.py", line 375, in forward
    return self.tr(p + self.linear(p)).unsqueeze(3).transpose(0, 3).reshape(b, self.c2, w, h)
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2 and 640x640)

**Comment by Gumpest** [comment]
您好 已经修复~
