### ISSUE TITLE
yolov5mTPH_std运行错误

### ISSUE THREAD

**Issue by wj51** [Gumpest/YOLOv5-Multibackbone-Compression#19]
Traceback (most recent call last):
  File "/wangjun/TPH_yolo/train.py", line 655, in <module>
    main(opt)
  File "/wangjun/TPH_yolo/train.py", line 552, in main
    train(opt.hyp, opt, device, callbacks)
  File "/wangjun/TPH_yolo/train.py", line 132, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/wangjun/TPH_yolo/models/yolo.py", line 103, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch], pruning=pruning)  # model, savelist
  File "/wangjun/TPH_yolo/models/yolo.py", line 305, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
  File "/wangjun/TPH_yolo/models/common.py", line 429, in __init__
    super().__init__(c1, c2, n, shortcut, g, e)
  File "/wangjun/TPH_yolo/models/common.py", line 416, in __init__
    self.cv1 = Conv(c1, c1_, 1, 1)
  File "/wangjun/TPH_yolo/models/common.py", line 325, in __init__
    self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 410, in __init__
    super(Conv2d, self).__init__(
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 83, in __init__
    self.reset_parameters()
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 86, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/init.py", line 379, in kaiming_uniform_
    fan = _calculate_correct_fan(tensor, mode)
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/init.py", line 348, in _calculate_correct_fan
    fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)
  File "/root/anaconda3/envs/tph/lib/python3.8/site-packages/torch/nn/init.py", line 280, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by Gumpest** [comment]
您好，已修复
