### ISSUE TITLE
yolov5lEfficientLite出错 

### ISSUE THREAD

**Issue by yyy8439** [Gumpest/YOLOv5-Multibackbone-Compression#22]
运行EfficientLite 时出错 错误信息：
Traceback (most recent call last):
  File "E://YOLOv5-Multibackbone-Compression-main/train.py", line 656, in <module>
    main(opt)
  File "E:/YOLOv5-Multibackbone-Compression-main/train.py", line 553, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:/cYOLOv5-Multibackbone-Compression-main/train.py", line 125, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "E:\YOLOv5-Multibackbone-Compression-main\models\yolo.py", line 103, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch], pruning=pruning)  # model, savelist
  File "E:\YOLOv5-Multibackbone-Compression-main\models\yolo.py", line 305, in parse_model
    m_ = nn.Sequential(*[m(*args) for _ in range(n)]) if n > 1 else m(*args)  # module
TypeError: __init__() missing 1 required positional argument: 'drop_connect_rate'

**Comment by Gumpest** [comment]
您好，已修复。请再次git pull

**Comment by yyy8439** [comment]
感谢回复  之后继续报错
Traceback (most recent call last):
  File "E:/YOLOv5-Multibackbone-Compression-main/train.py", line 656, in <module>
    main(opt)
  File "E:/YOLOv5-Multibackbone-Compression-main/train.py", line 553, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:/YOLOv5-Multibackbone-Compression-main/train.py", line 125, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "E:\YOLOv5-Multibackbone-Compression-main\models\yolo.py", line 120, in __init__
    self.info()
  File "E:\YOLOv5-Multibackbone-Compression-main\models\yolo.py", line 239, in info
    GFLOPS = model_info(self, verbose, img_size)
  File "E:\YOLOv5-Multibackbone-Compression-main\utils\torch_utils.py", line 243, in model_info
    return flops * img_size[0] / stride * img_size[1] / stride
UnboundLocalError: local variable 'flops' referenced before assignment

**Comment by Gumpest** [comment]
应该是from thop import profile加载错误，应该是您本地库的原因

**Comment by yyy8439** [comment]
问题已解决  十分感谢
